export const environment = {
  production: false,
  beServer: "https://xyz.csi.it",
  devBackendServer: "http://xyz",
  shibbolethSSOLogoutURL: "http://xyz/Shibboleth.sso/Logout",
  onAppExitURLOperatore: "https://xyz.csi.it/xyz/Shibboleth.sso/Logout",
  onAppExitURLCittadino: "https://xyz.csi.it/xyz/logout.do",
  onAppExitURL: "http://xyz/cms/pa/",
  contextRestBeServer: "https://xyz.csi.it/esenzioniweb/rest/services",
  publicPath: "/esenzioniweb",
  prenotazioni: "https://xyz/salute/prenotazioni",
   ticket: "https://xyz/xyz/RichiestaAuth.xml?servizio=ticket",
   salute: "https://xyz/salute/lamiasalute/",
   referti: "https://xyz/xyz/directServiceIndex.jsp?servizio=referto",
   fascicolos: "https://xyz/xyz/directServiceIndex.jsp?servizio=fas-sanitario",
   taccuino: "https://xyz/xyz/directServiceIndex.jsp?servizio=taccuino",
   fascicolof: "https://xyz/xyz/lamiasalute/fascicolofinanziario.php?servizio=fas-finanziario",
   screening: "https://xyz/xyz/riscre/index.php?servizio=screening",
   documenti: "https://xyz/xyz/directServiceIndex.jsp?servizio=uc",
   cambiomedico: "https://xyz/xyz/xyz/visualizza.php?servizio=medico",
   profilo: "https://xyz/xyz/lamiasalute/profilo.php?servizio=profilo",
   trova: "https://xyz/xyz/lamiasalute/mappa.php?servizio=trova&tipo=medici",
   valuta: "https://xyz.csi.it/it/form/customer-esenzione-ticket",
   mailassistenza: "xyz",
   mailassistenzapa: "xyz",
   deleghe: "https://xyz.csi.it/xyz/#/deleghe/piemonte/delegati"
};
