/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.esenred.esenredweb.business.aura.esenzionePatologia;

import java.io.File;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EsenzionePatologia", targetNamespace = "http://EsenzionePatologia.central.services.auraws.aura.csi.it", wsdlLocation = "C:\\Users\\Administrator\\Desktop\\EsenzionePatologia.wsdl")
public class EsenzionePatologia_Service
    extends Service
{

    private final static URL ESENZIONEPATOLOGIA_WSDL_LOCATION;
    private final static WebServiceException ESENZIONEPATOLOGIA_EXCEPTION;
    private final static QName ESENZIONEPATOLOGIA_QNAME = new QName("http://EsenzionePatologia.central.services.auraws.aura.csi.it", "EsenzionePatologia");

    static {
    	ClassLoader classloader = Thread.currentThread().getContextClassLoader();
        URL url = null;
        File file = null;
        WebServiceException e = null;
		try {
		//	file = new File(.getFile());
			url = classloader.getResourceAsStream("Wsdl/EsenzionePatologia.wsdl").getClass().getProtectionDomain().getCodeSource().getLocation(); 
		} catch (Exception e1) {
			
			//e1.printStackTrace();
		}
		ESENZIONEPATOLOGIA_WSDL_LOCATION = url;
		ESENZIONEPATOLOGIA_EXCEPTION = e;
    }

    public EsenzionePatologia_Service() {
        super(__getWsdlLocation(), ESENZIONEPATOLOGIA_QNAME);
    }

    public EsenzionePatologia_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ESENZIONEPATOLOGIA_QNAME, features);
    }

    public EsenzionePatologia_Service(URL wsdlLocation) {
        super(wsdlLocation, ESENZIONEPATOLOGIA_QNAME);
    }

    public EsenzionePatologia_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ESENZIONEPATOLOGIA_QNAME, features);
    }

    public EsenzionePatologia_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EsenzionePatologia_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EsenzionePatologiaSoap
     */
    @WebEndpoint(name = "EsenzionePatologiaSoap")
    public EsenzionePatologiaSoap getEsenzionePatologiaSoap() {
        return super.getPort(new QName("http://EsenzionePatologia.central.services.auraws.aura.csi.it", "EsenzionePatologiaSoap"), EsenzionePatologiaSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EsenzionePatologiaSoap
     */
    @WebEndpoint(name = "EsenzionePatologiaSoap")
    public EsenzionePatologiaSoap getEsenzionePatologiaSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://EsenzionePatologia.central.services.auraws.aura.csi.it", "EsenzionePatologiaSoap"), EsenzionePatologiaSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ESENZIONEPATOLOGIA_EXCEPTION!= null) {
            throw ESENZIONEPATOLOGIA_EXCEPTION;
        }
        return ESENZIONEPATOLOGIA_WSDL_LOCATION;
    }

}
