/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.esenred.esenredweb.business.aura.esenzionePatologia;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EsenzionePatologiaSoap", targetNamespace = "http://EsenzionePatologia.central.services.auraws.aura.csi.it")
@XmlSeeAlso({
    it.csi.esenred.esenredweb.business.aura.esenzionePatologia.ObjectFactory.class,
    it.csi.esenred.esenredweb.business.aura.esenzionePatologia.ObjectFactory.class
})
public interface EsenzionePatologiaSoap {


    /**
     * 
     * @param codiceFiscaleChiamante
     * @param dataAnnullamento
     * @param codiceFiscaleAssistito
     * @param dataInizioValidita
     * @param codiceEsenzione
     * @param dataFineValidita
     * @param listaDiagnosi
     * @return
     *     returns it.csi.esenred.esenredweb.business.aura.esenzionePatologia.EsenzionePatologiaRes
     */
    @WebMethod(action = "http://EsenzionePatologia.central.services.auraws.aura.csi.it/AURA.WS.EsenzionePatologia.esenzionePatologia")
    @WebResult(name = "esenzionePatologiaResult", targetNamespace = "http://EsenzionePatologia.central.services.auraws.aura.csi.it")
    @RequestWrapper(localName = "esenzionePatologia", targetNamespace = "http://EsenzionePatologia.central.services.auraws.aura.csi.it", className = "it.csi.esenred.esenredweb.business.aura.esenzionePatologia.EsenzionePatologia")
    @ResponseWrapper(localName = "esenzionePatologiaResponse", targetNamespace = "http://EsenzionePatologia.central.services.auraws.aura.csi.it", className = "it.csi.esenred.esenredweb.business.aura.esenzionePatologia.EsenzionePatologiaResponse")
    public EsenzionePatologiaRes esenzionePatologia(
        @WebParam(name = "codiceFiscaleChiamante", targetNamespace = "http://EsenzionePatologia.central.services.auraws.aura.csi.it")
        String codiceFiscaleChiamante,
        @WebParam(name = "codiceFiscaleAssistito", targetNamespace = "http://EsenzionePatologia.central.services.auraws.aura.csi.it")
        String codiceFiscaleAssistito,
        @WebParam(name = "codiceEsenzione", targetNamespace = "http://EsenzionePatologia.central.services.auraws.aura.csi.it")
        String codiceEsenzione,
        @WebParam(name = "dataInizioValidita", targetNamespace = "http://EsenzionePatologia.central.services.auraws.aura.csi.it")
        String dataInizioValidita,
        @WebParam(name = "dataFineValidita", targetNamespace = "http://EsenzionePatologia.central.services.auraws.aura.csi.it")
        String dataFineValidita,
        @WebParam(name = "dataAnnullamento", targetNamespace = "http://EsenzionePatologia.central.services.auraws.aura.csi.it")
        String dataAnnullamento,
        @WebParam(name = "listaDiagnosi", targetNamespace = "http://EsenzionePatologia.central.services.auraws.aura.csi.it")
        String listaDiagnosi);

}
