/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.esenred.esenredweb.business.aura.find;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import it.csi.esenred.esenredweb.business.model.impl.IntegrationClientImpl;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AnagrafeFind", targetNamespace = "http://AnagrafeFind.central.services.auraws.aura.csi.it")
public class AnagrafeFind
    extends Service
{

    private final static URL ANAGRAFEFIND_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(AnagrafeFind.class.getName());

    static {
        URL url = null;
        String urlWSDL = IntegrationClientImpl.getInstance().getUrlFindWSDL();
        try {
            URL baseUrl;
            baseUrl = AnagrafeFind.class.getResource(".");
            url = new URL(baseUrl, urlWSDL);
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: '"+urlWSDL+"', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ANAGRAFEFIND_WSDL_LOCATION = url;
    }

    public AnagrafeFind(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AnagrafeFind() {
        super(ANAGRAFEFIND_WSDL_LOCATION, new QName("http://AnagrafeFind.central.services.auraws.aura.csi.it", "AnagrafeFind"));
    }

    /**
     * 
     * @return
     *     returns AnagrafeFindSoap
     */
    @WebEndpoint(name = "AnagrafeFindSoap")
    public AnagrafeFindSoap getAnagrafeFindSoap() {
        return super.getPort(new QName("http://AnagrafeFind.central.services.auraws.aura.csi.it", "AnagrafeFindSoap"), AnagrafeFindSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AnagrafeFindSoap
     */
    @WebEndpoint(name = "AnagrafeFindSoap")
    public AnagrafeFindSoap getAnagrafeFindSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://AnagrafeFind.central.services.auraws.aura.csi.it", "AnagrafeFindSoap"), AnagrafeFindSoap.class, features);
    }

}
