/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.esenred.esenredweb.business.deleghebe;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import it.csi.esenred.esenredweb.business.model.impl.IntegrationClientImpl;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "DelegheCittadiniService", targetNamespace = "http://deleghebe.csi.it/", wsdlLocation = "file:/C:/axis-1_4/DelegheCittadiniService.wsdl")
public class DelegheCittadiniService_Service
    extends Service
{

    private final static URL DELEGHECITTADINISERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(it.csi.esenred.esenredweb.business.deleghebe.DelegheCittadiniService_Service.class.getName());

    static {
        URL url = null;
        String urlWSDL = IntegrationClientImpl.getInstance().getUrlGetDeleghe();
        try {
            URL baseUrl;
            baseUrl =DelegheCittadiniService_Service.class.getResource(".");
            url = new URL(baseUrl, urlWSDL);
           // url = new URL(baseUrl, "file:/C:/axis-1_4/DelegheCittadiniService.wsdl");
        } catch (MalformedURLException e) {
        	 logger.warning("Failed to create URL for the wsdl Location: '"+urlWSDL+"', retrying as a local file");
           // logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/axis-1_4/DelegheCittadiniService.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        DELEGHECITTADINISERVICE_WSDL_LOCATION = url;
    }

    public DelegheCittadiniService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DelegheCittadiniService_Service() {
        super(DELEGHECITTADINISERVICE_WSDL_LOCATION, new QName("http://deleghebe.csi.it/", "DelegheCittadiniService"));
    }

    /**
     * 
     * @return
     *     returns DelegheCittadiniService
     */
    @WebEndpoint(name = "DelegheCittadiniServiceImplPort")
    public DelegheCittadiniService getDelegheCittadiniServiceImplPort() {
        return super.getPort(new QName("http://deleghebe.csi.it/", "DelegheCittadiniServiceImplPort"), DelegheCittadiniService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DelegheCittadiniService
     */
    @WebEndpoint(name = "DelegheCittadiniServiceImplPort")
    public DelegheCittadiniService getDelegheCittadiniServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://deleghebe.csi.it/", "DelegheCittadiniServiceImplPort"), DelegheCittadiniService.class, features);
    }

}
