/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.esenred.esenredweb.business.aura.getEsenred;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GetEsenRedSoap", targetNamespace = "http://GetEsenRed.central.services.auraws.aura.csi.it")
@XmlSeeAlso({
    it.csi.esenred.esenredweb.business.aura.getEsenred.ObjectFactory.class
})
public interface GetEsenRedSoap {


    /**
     * 
     * @param idAURA
     * @param tipoUser
     * @return
     *     returns it.csi.esenred.esenredweb.business.aura.getEsenred.GetEsenRedRes
     */
    @WebMethod(operationName = "GetEsenRed", action = "http://GetEsenRed.central.services.auraws.aura.csi.it/AURA.WS.GetEsenRed.GetEsenRed")
    @WebResult(name = "GetEsenRedResult", targetNamespace = "http://GetEsenRed.central.services.auraws.aura.csi.it")
    @RequestWrapper(localName = "GetEsenRed", targetNamespace = "http://GetEsenRed.central.services.auraws.aura.csi.it", className = "it.csi.esenred.esenredweb.business.aura.getEsenred.GetEsenRed")
    @ResponseWrapper(localName = "GetEsenRedResponse", targetNamespace = "http://GetEsenRed.central.services.auraws.aura.csi.it", className = "it.csi.esenred.esenredweb.business.aura.getEsenred.GetEsenRedResponse")
    public GetEsenRedRes getEsenRed(
        @WebParam(name = "idAURA", targetNamespace = "http://GetEsenRed.central.services.auraws.aura.csi.it")
        Long idAURA,
        @WebParam(name = "tipoUser", targetNamespace = "http://GetEsenRed.central.services.auraws.aura.csi.it")
        String tipoUser);

}
