/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.esenred.esenredweb.business.aura.getEsenred;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "GetEsenRed", targetNamespace = "http://GetEsenRed.central.services.auraws.aura.csi.it", wsdlLocation = "file:/C:/axis-1_4/GetEsenRedEnsemble3.wsdl")
public class GetEsenRed_Service
    extends Service
{

    private final static URL GETESENRED_WSDL_LOCATION;
    private final static WebServiceException GETESENRED_EXCEPTION;
    private final static QName GETESENRED_QNAME = new QName("http://GetEsenRed.central.services.auraws.aura.csi.it", "GetEsenRed");

    static {
    	ClassLoader classloader = Thread.currentThread().getContextClassLoader();
        URL url = null;
        File file = null;
        WebServiceException e = null;
		try {
		//	file = new File(.getFile());
			url = classloader.getResourceAsStream("Wsdl/GetEsenRedEnsemble.wsdl").getClass().getProtectionDomain().getCodeSource().getLocation(); 
		} catch (Exception e1) {
			
			//e1.printStackTrace();
		}
        GETESENRED_WSDL_LOCATION = url;
        GETESENRED_EXCEPTION = e;
    }

    public GetEsenRed_Service() {
        super(__getWsdlLocation(), GETESENRED_QNAME);
    }

    public GetEsenRed_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), GETESENRED_QNAME, features);
    }

    public GetEsenRed_Service(URL wsdlLocation) {
        super(wsdlLocation, GETESENRED_QNAME);
    }

    public GetEsenRed_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, GETESENRED_QNAME, features);
    }

    public GetEsenRed_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetEsenRed_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns GetEsenRedSoap
     */
    @WebEndpoint(name = "GetEsenRedSoap")
    public GetEsenRedSoap getGetEsenRedSoap() {
        return super.getPort(new QName("http://GetEsenRed.central.services.auraws.aura.csi.it", "GetEsenRedSoap"), GetEsenRedSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetEsenRedSoap
     */
    @WebEndpoint(name = "GetEsenRedSoap")
    public GetEsenRedSoap getGetEsenRedSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://GetEsenRed.central.services.auraws.aura.csi.it", "GetEsenRedSoap"), GetEsenRedSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (GETESENRED_EXCEPTION!= null) {
            throw GETESENRED_EXCEPTION;
        }
        return GETESENRED_WSDL_LOCATION;
    }

}
