/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.esenred.esenredweb.business.aura.insertautocertesered;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "InsertAutocertEseRedSoap", targetNamespace = "http://InsertAutocertEseRed.central.services.auraws.aura.csi.it")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InsertAutocertEseRedSoap {


    /**
     * 
     * @param newEseRed
     * @return
     *     returns it.csi.esenred.esenredweb.business.aura.insertautocertesered.Response
     */
    @WebMethod(operationName = "InsertAutocertEseRed", action = "http://InsertAutocertEseRed.central.services.auraws.aura.csi.it/AURA.WS.InsertAutocertEseRed.InsertAutocertEseRed")
    @WebResult(name = "InsertAutocertEseRedResult", targetNamespace = "http://InsertAutocertEseRed.central.services.auraws.aura.csi.it")
    @RequestWrapper(localName = "InsertAutocertEseRed", targetNamespace = "http://InsertAutocertEseRed.central.services.auraws.aura.csi.it", className = "it.csi.esenred.esenredweb.business.aura.insertautocertesered.InsertAutocertEseRed")
    @ResponseWrapper(localName = "InsertAutocertEseRedResponse", targetNamespace = "http://InsertAutocertEseRed.central.services.auraws.aura.csi.it", className = "it.csi.esenred.esenredweb.business.aura.insertautocertesered.InsertAutocertEseRedResponse")
    public Response insertAutocertEseRed(
        @WebParam(name = "newEseRed", targetNamespace = "http://InsertAutocertEseRed.central.services.auraws.aura.csi.it")
        Request newEseRed);

}
