/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.esenred.esenredweb.business.aura.iterrogamefesenredd;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.2
 * 2019-12-10T17:43:36.746+01:00
 * Generated source version: 2.7.2
 * 
 */
@WebService(targetNamespace = "http://InterrogaMefEsenredd.central.services.auraws.aura.csi.it", name = "InterrogaMefEsenreddSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface InterrogaMefEsenreddSoap {

    @WebResult(name = "InterrogaMefEsenreddResult", targetNamespace = "http://InterrogaMefEsenredd.central.services.auraws.aura.csi.it")
    @RequestWrapper(localName = "InterrogaMefEsenredd", targetNamespace = "http://InterrogaMefEsenredd.central.services.auraws.aura.csi.it", className = "it.csi.esenred.esenredweb.business.aura.iterrogamefesenredd.InterrogaMefEsenredd")
    @WebMethod(operationName = "InterrogaMefEsenredd", action = "http://InterrogaMefEsenredd.central.services.auraws.aura.csi.it/AURA.WS.InterrogaMefEsenredd.InterrogaMefEsenredd")
    @ResponseWrapper(localName = "InterrogaMefEsenreddResponse", targetNamespace = "http://InterrogaMefEsenredd.central.services.auraws.aura.csi.it", className = "it.csi.esenred.esenredweb.business.aura.iterrogamefesenredd.InterrogaMefEsenreddResponse")
    public it.csi.esenred.esenredweb.business.aura.iterrogamefesenredd.InterrogaMefEsenreddRes interrogaMefEsenredd(
        @WebParam(name = "CF", targetNamespace = "http://InterrogaMefEsenredd.central.services.auraws.aura.csi.it")
        java.lang.String cf
    );
}
