/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.esenred.esenredweb.business.aura.get;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import it.csi.esenred.esenredweb.business.model.impl.IntegrationClientImpl;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "AnagrafeSanitaria", targetNamespace = "http://AnagrafeSanitaria.central.services.auraws.aura.csi.it", wsdlLocation = "")
public class AnagrafeSanitaria
    extends Service
{

    private final static URL ANAGRAFESANITARIA_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(it.csi.esenred.esenredweb.business.aura.get.AnagrafeSanitaria.class.getName());

    static {
        URL url = null;
        String urlWSDL = IntegrationClientImpl.getInstance().getUrlGetWSDL();
        try {
            URL baseUrl;
            baseUrl = AnagrafeSanitaria.class.getResource(".");
            url = new URL(baseUrl, urlWSDL);//"https://xyz/sanitxens/csp/aura/AURA.WS.AnagrafeSanitariaNew.cls?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: '"+urlWSDL+"', retrying as a local file");//;''https://xyz/sanitxens/csp/aura/AURA.WS.AnagrafeSanitariaNew.cls?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        ANAGRAFESANITARIA_WSDL_LOCATION = url;
    }

    public AnagrafeSanitaria(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AnagrafeSanitaria() {
        super(ANAGRAFESANITARIA_WSDL_LOCATION, new QName("http://AnagrafeSanitaria.central.services.auraws.aura.csi.it", "AnagrafeSanitaria"));
    }

    /**
     * 
     * @return
     *     returns AnagrafeSanitariaSoap
     */
    @WebEndpoint(name = "AnagrafeSanitariaSoap")
    public AnagrafeSanitariaSoap getAnagrafeSanitariaSoap() {
        return super.getPort(new QName("http://AnagrafeSanitaria.central.services.auraws.aura.csi.it", "AnagrafeSanitariaSoap"), AnagrafeSanitariaSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AnagrafeSanitariaSoap
     */
    @WebEndpoint(name = "AnagrafeSanitariaSoap")
    public AnagrafeSanitariaSoap getAnagrafeSanitariaSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://AnagrafeSanitaria.central.services.auraws.aura.csi.it", "AnagrafeSanitariaSoap"), AnagrafeSanitariaSoap.class, features);
    }

}
