/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.esenred.esenredweb.business.aura.iterrogamefesenredd;

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.2
 * 2019-12-10T17:43:36.755+01:00
 * Generated source version: 2.7.2
 * 
 */
@WebServiceClient(name = "InterrogaMefEsenredd", 
                  wsdlLocation = "file:/C:/Users/Administrator/Desktop/InterrogaMefEsenredd.wsdl",
                  targetNamespace = "http://InterrogaMefEsenredd.central.services.auraws.aura.csi.it") 
public class InterrogaMefEsenredd_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://InterrogaMefEsenredd.central.services.auraws.aura.csi.it", "InterrogaMefEsenredd");
    public final static QName InterrogaMefEsenreddSoap = new QName("http://InterrogaMefEsenredd.central.services.auraws.aura.csi.it", "InterrogaMefEsenreddSoap");
    static {
    	ClassLoader classloader = Thread.currentThread().getContextClassLoader();
        URL url = null;
        File file = null;
        WebServiceException e = null;
		try {
		//	file = new File(.getFile());
			url = classloader.getResourceAsStream("Wsdl/InterrogaMefEsenredd.wsdl").getClass().getProtectionDomain().getCodeSource().getLocation(); 
		} catch (Exception e1) {
			
			//e1.printStackTrace();
		}
        WSDL_LOCATION = url;
    }

    public InterrogaMefEsenredd_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public InterrogaMefEsenredd_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InterrogaMefEsenredd_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public InterrogaMefEsenredd_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public InterrogaMefEsenredd_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public InterrogaMefEsenredd_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns InterrogaMefEsenreddSoap
     */
    @WebEndpoint(name = "InterrogaMefEsenreddSoap")
    public InterrogaMefEsenreddSoap getInterrogaMefEsenreddSoap() {
        return super.getPort(InterrogaMefEsenreddSoap, InterrogaMefEsenreddSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InterrogaMefEsenreddSoap
     */
    @WebEndpoint(name = "InterrogaMefEsenreddSoap")
    public InterrogaMefEsenreddSoap getInterrogaMefEsenreddSoap(WebServiceFeature... features) {
        return super.getPort(InterrogaMefEsenreddSoap, InterrogaMefEsenreddSoap.class, features);
    }

}
