/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.esenred.esenredweb.business.aura.chiusuraesenzionecertificata;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2019-12-12T10:30:12.760+01:00
 * Generated source version: 2.7.9
 * 
 */
@WebServiceClient(name = "ChiusuraEsenRed", 
                  wsdlLocation = "file:/C:/Users/Administrator/Desktop/ChiusuraEsenRed.wsdl",
                  targetNamespace = "http://ChiusuraEsenRed.central.services.auraws.aura.csi.it") 
public class ChiusuraEsenRed_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ChiusuraEsenRed.central.services.auraws.aura.csi.it", "ChiusuraEsenRed");
    public final static QName ChiusuraEsenRedSoap = new QName("http://ChiusuraEsenRed.central.services.auraws.aura.csi.it", "ChiusuraEsenRedSoap");
    static {
        URL url = null;
        ClassLoader classloader = Thread.currentThread().getContextClassLoader();
        try {
    			url = classloader.getResourceAsStream("Wsdl/ChiusuraEsenRed.wsdl").getClass().getProtectionDomain().getCodeSource().getLocation(); 
    		} catch (Exception e1) {
    		}
        WSDL_LOCATION = url;
    }

    public ChiusuraEsenRed_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ChiusuraEsenRed_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ChiusuraEsenRed_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ChiusuraEsenRed_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ChiusuraEsenRed_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public ChiusuraEsenRed_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns ChiusuraEsenRedSoap
     */
    @WebEndpoint(name = "ChiusuraEsenRedSoap")
    public ChiusuraEsenRedSoap getChiusuraEsenRedSoap() {
        return super.getPort(ChiusuraEsenRedSoap, ChiusuraEsenRedSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ChiusuraEsenRedSoap
     */
    @WebEndpoint(name = "ChiusuraEsenRedSoap")
    public ChiusuraEsenRedSoap getChiusuraEsenRedSoap(WebServiceFeature... features) {
        return super.getPort(ChiusuraEsenRedSoap, ChiusuraEsenRedSoap.class, features);
    }

}
