/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/
package it.csi.esenred.esenredweb.business.aura.chiusuraesenzionecertificata;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2019-12-12T10:30:12.752+01:00
 * Generated source version: 2.7.9
 * 
 */
@WebService(targetNamespace = "http://ChiusuraEsenRed.central.services.auraws.aura.csi.it", name = "ChiusuraEsenRedSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface ChiusuraEsenRedSoap {

    @WebResult(name = "ChiusuraEsenRedResult", targetNamespace = "http://ChiusuraEsenRed.central.services.auraws.aura.csi.it")
    @RequestWrapper(localName = "ChiusuraEsenRed", targetNamespace = "http://ChiusuraEsenRed.central.services.auraws.aura.csi.it", className = "it.csi.esenred.esenredweb.business.aura.chiusuraesenzionecertificata.ChiusuraEsenRed")
    @WebMethod(operationName = "ChiusuraEsenRed", action = "http://ChiusuraEsenRed.central.services.auraws.aura.csi.it/AURA.WS.ChiusuraEsenRed.ChiusuraEsenRed")
    @ResponseWrapper(localName = "ChiusuraEsenRedResponse", targetNamespace = "http://ChiusuraEsenRed.central.services.auraws.aura.csi.it", className = "it.csi.esenred.esenredweb.business.aura.chiusuraesenzionecertificata.ChiusuraEsenRedResponse")
    public it.csi.esenred.esenredweb.business.aura.chiusuraesenzionecertificata.ChiusuraEsenRedRes chiusuraEsenRed(
        @WebParam(name = "codiceFiscaleChiamante", targetNamespace = "http://ChiusuraEsenRed.central.services.auraws.aura.csi.it")
        java.lang.String codiceFiscaleChiamante,
        @WebParam(name = "codiceEsenzione", targetNamespace = "http://ChiusuraEsenRed.central.services.auraws.aura.csi.it")
        java.lang.String codiceEsenzione,
        @WebParam(name = "dataInizioValidita", targetNamespace = "http://ChiusuraEsenRed.central.services.auraws.aura.csi.it")
        java.lang.String dataInizioValidita,
        @WebParam(name = "codiceFiscaleAssistito", targetNamespace = "http://ChiusuraEsenRed.central.services.auraws.aura.csi.it")
        java.lang.String codiceFiscaleAssistito
    );
}
