/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.esenred.esenredweb.business.aura.insertautocertesered;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import it.csi.esenred.esenredweb.business.model.impl.IntegrationClientImpl;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "InsertAutocertEseRed", targetNamespace = "http://InsertAutocertEseRed.central.services.auraws.aura.csi.it")
public class InsertAutocertEseRed_Service
    extends Service
{

    private final static URL INSERTAUTOCERTESERED_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(it.csi.esenred.esenredweb.business.aura.insertautocertesered.InsertAutocertEseRed_Service.class.getName());

    static {
        URL url = null;
        String urlWSDL = IntegrationClientImpl.getInstance().getUrlInsertWSDL();
        try {
            URL baseUrl;
            baseUrl = it.csi.esenred.esenredweb.business.aura.insertautocertesered.InsertAutocertEseRed_Service.class.getResource(".");
            url = new URL(baseUrl, urlWSDL);//"https://xyz/sanitxens/AURA.WS.InsertAutocertEseRed.cls?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: '"+urlWSDL+"', retrying as a local file");// 'https://xyz/sanitxens/AURA.WS.InsertAutocertEseRed.cls?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        INSERTAUTOCERTESERED_WSDL_LOCATION = url;
    }

    public InsertAutocertEseRed_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InsertAutocertEseRed_Service() {
        super(INSERTAUTOCERTESERED_WSDL_LOCATION, new QName("http://InsertAutocertEseRed.central.services.auraws.aura.csi.it", "InsertAutocertEseRed"));
    }

    /**
     * 
     * @return
     *     returns InsertAutocertEseRedSoap
     */
    @WebEndpoint(name = "InsertAutocertEseRedSoap")
    public InsertAutocertEseRedSoap getInsertAutocertEseRedSoap() {
        return super.getPort(new QName("http://InsertAutocertEseRed.central.services.auraws.aura.csi.it", "InsertAutocertEseRedSoap"), InsertAutocertEseRedSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InsertAutocertEseRedSoap
     */
    @WebEndpoint(name = "InsertAutocertEseRedSoap")
    public InsertAutocertEseRedSoap getInsertAutocertEseRedSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://InsertAutocertEseRed.central.services.auraws.aura.csi.it", "InsertAutocertEseRedSoap"), InsertAutocertEseRedSoap.class, features);
    }

}
