/*******************************************************************************
* Copyright Regione Piemonte - 2022
* SPDX-License-Identifier: EUPL-1.2
******************************************************************************/

package it.csi.esenred.esenredweb.business.aura.chiusuraesenzionecertificata;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.9
 * 2019-12-12T10:30:12.708+01:00
 * Generated source version: 2.7.9
 * 
 */
public final class ChiusuraEsenRedSoap_ChiusuraEsenRedSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://ChiusuraEsenRed.central.services.auraws.aura.csi.it", "ChiusuraEsenRed");

    private ChiusuraEsenRedSoap_ChiusuraEsenRedSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ChiusuraEsenRed_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ChiusuraEsenRed_Service ss = new ChiusuraEsenRed_Service(wsdlURL, SERVICE_NAME);
        ChiusuraEsenRedSoap port = ss.getChiusuraEsenRedSoap();  
        
        {
        System.out.println("Invoking chiusuraEsenRed...");
        java.lang.String _chiusuraEsenRed_codiceFiscaleChiamante = "";
        java.lang.String _chiusuraEsenRed_codiceEsenzione = "";
        java.lang.String _chiusuraEsenRed_dataInizioValidita = "";
        java.lang.String _chiusuraEsenRed_codiceFiscaleAssistito = "";
        it.csi.esenred.esenredweb.business.aura.chiusuraesenzionecertificata.ChiusuraEsenRedRes _chiusuraEsenRed__return = port.chiusuraEsenRed(_chiusuraEsenRed_codiceFiscaleChiamante, _chiusuraEsenRed_codiceEsenzione, _chiusuraEsenRed_dataInizioValidita, _chiusuraEsenRed_codiceFiscaleAssistito);
        System.out.println("chiusuraEsenRed.result=" + _chiusuraEsenRed__return);


        }

        System.exit(0);
    }

}
